version: "3.7"

networks:
  app-network:

services:
  nginx:
    build:
      context: ./.docker/nginx
    ports:
      - 3000:80
    volumes:
      - ./public:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  php-fpm:
    build:
      context: ./.docker/php-fpm
    volumes:
      - ./public:/var/www
    networks:
      - app-network

  mysql:
    build:
      context: ./.docker/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    volumes:
      - ./.docker/mysql/db-data:/var/lib/mysql
    networks:
      - app-network